language: java

script: mvn clean verify

jdk:
    - oraclejdk7
    - openjdk7

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com

after_success:
  - mvn jacoco:report coveralls:jacoco